services:
  mysql:
    image: mysql:8.0
    container_name: adtech_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: adtech_db
      MYSQL_USER: adtech_user
      MYSQL_PASSWORD: adtech_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - adtech_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: adtech_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - adtech_network

  adtech_python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adtech_python
    volumes:
      - ./data:/app/data
      - ./output:/app/output           # <-- для експорту результатів з контейнера
      - ./transforms_data.py:/app/transforms_data.py
      - ./homework2.py:/app/homework2.py
      - ./load_to_mongodb.py:/app/load_to_mongodb.py
      - ./analyze_mongo.py:/app/analyze_mongo.py
      - ./requirements.txt:/app/requirements.txt
    working_dir: /app
    depends_on:
      - mysql
    networks:
      - adtech_network

  mongo:
    image: mongo:6.0
    container_name: adtech_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - adtech_network

  mongo-express:
    image: mongo-express
    restart: always
    container_name: adtech_mongo_express
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    ports:
      - "8081:8081"
    networks:
      - adtech_network
volumes:
  mysql_data:
  mongo_data:

networks:
  adtech_network:
    driver: bridge
